### ISSUE TITLE
TypeError for assigning websocket provider

### ISSUE THREAD

**Issue by tpalaz** [Rubilmax/ethers-multicall-provider#31]
## Current Behavior
Argument of type 'WebSocketProvider' is not assignable to parameter of type 'BaseProvider'.
  Type 'WebSocketProvider' is missing the following properties from type 'BaseProvider': _networkPromise, _events, formatter, _emitted, and 37 more.ts(2345)

    const wsProvider = new WebSocketProvider("websocketConnectionString");
    const multicallProvider = MulticallWrapper.wrap(wsProvider);

## Expected Behavior

Successfully wrap websocket provider with mutlicallwrapper

## Steps to Reproduce the Problem

  1. Create a new ethers websocketprovider
  2. Create a new multicall wrapper and wrap the previous websocket provider

## Environment
- Ethers Version: ^6.3.0
- Version: ^3.0.1
- Platform:  Win10
- Node.js Version 18.15.0

**Comment by tpalaz** [comment]
Note that bumping down ethers to 5.0 fixes the issue. Probably to do with ethers re-typing of providers in ^6.0

**Comment by Rubilmax** [comment]
Thanks for your detailed explanation and reproducible setup. I'll release a version dedicated to ethers-v6 then!

**Comment by Rubilmax** [comment]
I can't prioritize this in the short term. I started something but ethers-v6 does not make it easy to have a multicall provider. If you've got time, feel free to help!
