### ISSUE TITLE
Add support for older build setups (up to es5)

### ISSUE THREAD

**Issue by vad99lord** [Rubilmax/ethers-multicall-provider#44]
## Current Behavior

I'm trying to use the package in a legacy environment, where new features (eg. numeric separators) are not supported and node modules packages are not transpiled down. My simplified setup is in a repro [repo](https://github.com/vad99lord/ethers-multicall-repro)
If you try to start the project there are babel loader errors, such as:
```
Module parse failed: Identifier directly after number (40:104)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   static wrap(provider) {
|     let delay = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 16;
>     let maxMulticallDataLength = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : 200_000;
```

## Expected Behavior

Currently, the project seems to be using [esnext target](https://github.com/Rubilmax/ethers-multicall-provider/blob/81fce8b6f638861c0d8a7ac071066ad218e460f9/tsconfig.json#L4)
I think this package should support the same es version as ethers package, which is es5 for [ethers v5.7.2](https://github.com/ethers-io/ethers.js/blob/ec1b9583039a14a0e0fa15d0a2a6082a2f41cf5b/tsconfig.package.json#L24) 

## Steps to Reproduce the Problem

  1. use node 16 to build repro package
  1. npm install
  1. npm start

## Environment

- Version: 3.0.3
- Platform: any
- Node.js Version: 16.20

**Comment by Rubilmax** [comment]
Should be fixed with: https://github.com/Rubilmax/ethers-multicall-provider/commit/6ac439343353ff115e0bf317511434df55585d12

**Comment by vad99lord** [comment]
Works fine for me in the latest version, thanks!

**Comment by Rubilmax** [comment]
Thanks for reporting!
