### ISSUE TITLE
BaseProvider can be replaced by Provider

### ISSUE THREAD

**Issue by julien-devatom** [Rubilmax/ethers-multicall-provider#45]
## Current Behavior

The wrapped provider is typed as an extension of the BaseProvider. However [BaseProvider](https://github.com/ethers-io/ethers.js/blob/v5.7/packages/providers/src.ts/base-provider.ts#L702C14-L702C26) is an extension of `Provider`. In my understanding, there are no properties used by the wrapper that are defined in `BaseProvider` and not in `Provider`. 

And because a lot of providers are not typed as extending `BaseProvider` (for example, `signer.provider` is typed as `Provider`) so we have to force the type (operation that can be destructive if the Wrapper is using `BaseProvider` specific fields). 

## Expected Behavior
The wrapper must be able to wrap all provider extending Provider.

**Comment by Rubilmax** [comment]
`BaseProvider` implements the `Provider` interface and exposes `network` field and `perform` function, which the `MulticallProvider` overwrites. It is the most efficient way to build such a provider. What's the usecase you have where you need to type it `Provider` instead of `BaseProvider`?

**Comment by julien-devatom** [comment]
My point is, when we are using `signer.provider`, we have a `Provider` (and not a `BaseProvider`, see code [here](https://github.com/ethers-io/ethers.js/blob/v5.7/packages/abstract-signer/src.ts/index.ts#L59)) 
IMO we can have a Provider to wrap and find a way to build a `BaseProvider` from a `Provider`.
In fact, the provider is a JsonRpcProvider which is implementing BaseProvider, but typed as Provider..

See [here](https://github.com/morpho-org/morpho-aave-v3-sdk/blob/main/tests/e2e/transactions.test.ts#L64) what we are doing as workaround. 

this is a good refactor to improve the multicall adoption since usage is going to be generalized to `Provider` interface

**Comment by Rubilmax** [comment]
Unfortunately, there's no workaround other than a complete rewrite of the package, because the `network` field is used for efficient purposes and the `perform` function is overwritten to be able to batch RPC calls natively...

**Comment by julien-devatom** [comment]
Mmh and having a `MulticallWrapper.fromProvider(provider: Provider)` that is creating a `BaseProvider` from a `Provider`, is it possible or is `Provider` interface too low level? (haven't checked the code in depth)

**Comment by Rubilmax** [comment]
The `Provider` interface is indeed actually too low-level: it misses the definition of the `network` field and the `perform` function.
