### ISSUE TITLE
Cannot wrap the provider with getDefaultProvider.

### ISSUE THREAD

**Issue by ashwinYardi** [Rubilmax/ethers-multicall-provider#53]
## Current Behavior

<img width="1282" alt="image" src="https://github.com/Rubilmax/ethers-multicall-provider/assets/43699109/042d115f-730e-44a0-849e-0d22a57e0ed8">

As you can see in the image above, it throws type error when I try to wrap the provider.

Here is the error: 
`Argument of type 'AbstractProvider' is not assignable to parameter of type 'Provider'.
  Type 'AbstractProvider' is missing the following properties from type 'Provider': getGasPrice, getStorageAt, sendTransaction, getBlockWithTransactions, _isProvider ts(2345)`
  
## Expected Behavior

As per the docs, the above code should work without any type errors. 

## Environment

- Version: 5.0.0
- Ethers: 6.7.1
- Platform: Mac
- Node.js Version: v16.20.0

**Comment by Rubilmax** [comment]
I tried reproducing your bug but I can't manage to have a type error when trying to wrap `getDefaultProvider`
In fact, `getDefaultProvider` returns an `AbstractProvider` while `MulticallWrapper.wrap` expects an `AbstractProvider`, so it should work

Th thing is typescript highlights that the type returned by `getDefaultProvider` in your example is `Provider` ; which is incompatible and seems to behave like if ethers was v5. Please check your ethers version and update it to v6. There may be other packages that require ethers v5 to work and prevent you from updating it to v6
