### ISSUE TITLE
Browser builds?

### ISSUE THREAD

**Issue by kaliubuntu0206** [Rubilmax/ethers-multicall-provider#54]
Hello,

Thank you for shipping a great package!

It would be great if you could also ship the package with browser builds ( with like rollup or webpack, ethers does it here https://github.com/ethers-io/ethers.js/blob/main/package.json#L116 ).

Thanks!

**Comment by Rubilmax** [comment]
Thanks for opening the issue!

I'm not sure to get it, could you describe the use case?

I particularly don't understand what prevents you from using this package in a React-based (or any other UI framework) app using a webpack pipeline?

**Comment by kaliubuntu0206** [comment]
@Rubilmax I do some call experiments on bare javascript and would like to have multicallwrapper as a global object ( In this case window )
