### ISSUE TITLE
Not assignable to parameter of type 'AbstractProvider'

### ISSUE THREAD

**Issue by mihaic195** [Rubilmax/ethers-multicall-provider#59]
## Current Behavior

![Screenshot 2024-01-12 at 14 52 39](https://github.com/Rubilmax/ethers-multicall-provider/assets/34626017/1d74ff0c-91c0-430c-a771-db0d78186065)

Here is the error:
```
Argument of type 'JsonRpcProvider' is not assignable to parameter of type 'AbstractProvider'.
  Type 'JsonRpcProvider' is missing the following properties from type 'AbstractProvider': #private, provider, plugins, attachPlugin, and 22 more.ts(2345)
```

## Expected Behavior

There should be no type errors.

## Environment

- Version: `"ethers-multicall-provider": "^3.1.2",`
- Platform: Mac
- Node.js Version: 18.17.0
- Ethers.js version: `"ethers": "^5.7.2",`

**Comment by Rubilmax** [comment]
Hi, support for ethers v5 dropped from v4.0.0 so I would recommend switching to ethers v6 and use the latest v6.0.0 version which solves this issue

**Comment by mihaic195** [comment]
Thanks for the quick reply!
The problem is that it's a larger project, and it's difficult to migrate to Ethers v6 easily. I was hoping there was a quick fix until handling migration to Ethers v6.

**Comment by Rubilmax** [comment]
It is weird that you encounter this issue in v3.1.2 where the provider is expected to inherit `Provider` and not `AbstractProvider`: https://github.com/Rubilmax/ethers-multicall-provider/blob/828fdb1ec712d2bc61b8a3f3a80b2ec22b8fdf9c/src/multicall-provider.ts

Are you sure you are on version v3.1.2 (latest for ethers v5)?
What you can do is try with earlier versions like v3.1.0
