### ISSUE TITLE
weird ethersv6 cache

### ISSUE THREAD

**Issue by yanfeizuo** [Rubilmax/ethers-multicall-provider#60]
When using the ethersv6 version, there is always a cache and there is no way to update the data.

**Comment by Rubilmax** [comment]
Hi, indeed there's cache on calls made at the same block number, on the same contract, with the same calldata. Why would you want to update the cache? Why would the data change on the blockchain?

**Comment by Rubilmax** [comment]
So there was the issue that all queries made at the "latest" block tag were cached... which is unexpected
