### ISSUE TITLE
Type mismatch for the AbstractProvider when trying to wrap ethers v6 JsonRPCProvider.

### ISSUE THREAD

**Issue by ashwinYardi** [Rubilmax/ethers-multicall-provider#61]
## Current Behavior
<img width="1190" alt="Screenshot 2024-02-08 at 10 29 36 AM" src="https://github.com/Rubilmax/ethers-multicall-provider/assets/43699109/09cf4437-cee4-4e8a-a44b-40e015e779a3">

As shown in the above image, in both the cases, when trying to wrap AbstractProvider, the type error is shown: 

```
Argument of type 'import(".../node_modules/ethers/lib.commonjs/providers/abstract-provider").AbstractProvider' is not assignable to parameter of type 'import(".../node_modules/ethers-multicall-provider/node_modules/ethers/lib.commonjs/providers/abstract-provider").AbstractProvider'.
  
 Property '#private' in type 'AbstractProvider' refers to a different member that cannot be accessed from within type 'AbstractProvider'.
 ```
So apparently, two different variations of the type AbstractProvider are being used which is causing the collision.

AbstractProvider returned by `getDefaultProvider` in ethers  v6 is different that what is epected by `ethers-multicall-provider`

## Environment

- Version:  "ethers": "^6.7.1", "ethers-multicall-provider": "6.0.3",
- Platform: mac
- Node.js Version: v16.20

**Comment by ashwinYardi** [comment]
One more example: 

<img width="1190" alt="image" src="https://github.com/Rubilmax/ethers-multicall-provider/assets/43699109/4df5fd16-14a8-44cc-9183-5216dffad69b">


The error is the same. AbstractProvider from ethers lib inside ethers-multicall-provider and AbstractProvider driectly imported from ethers clash with each other. :(

**Comment by Rubilmax** [comment]
Can you ref a repository pls? Every time i had this error there were 2 versions of ethers installed at the same time. I need to check your lock file

**Comment by ashwinYardi** [comment]
Hey will quickly spin up a project and share the similar setup with you.

**Comment by ashwinYardi** [comment]
Hey, so I was not getting this error in the new project that I had setup. So after your hint that this could be due to dependency issues, I cleaned the cache, deleted the lock file, reinstalled ethers and ethers-multicall-provider andd BAMM, the type erros are gone. 

Not sure, what was causing the issue, but for now got it working. Thank you so much!

**Comment by Rubilmax** [comment]
Great! Hopefully it'll be helpful to others later!
