### ISSUE TITLE
zkSync Sepolia Testnet

### ISSUE THREAD

**Issue by Terpasaurus** [Rubilmax/ethers-multicall-provider#62]
Hello Rubilmax, Goerlie has been deprecated, please add zkSync Sepolia Testnet to:

export const multicall3ChainAddress: { [chainId: number]: string } = {
  280: multicall3ZkSyncAddress, // zkSync Ero Goerli
  324: multicall3ZkSyncAddress, // zkSync Era
};

Info:

export const zkSyncSepoliaTestnet = /*#__PURE__*/ defineChain(
  {
    id: 300,
    name: 'zkSync Sepolia Testnet',
    network: 'zksync-sepolia-testnet',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: {
      default: {
        http: ['https://sepolia.era.zksync.dev'],
        webSocket: ['wss://sepolia.era.zksync.dev/ws'],
      },
      public: {
        http: ['https://sepolia.era.zksync.dev'],
        webSocket: ['wss://sepolia.era.zksync.dev/ws'],
      },
    },
    blockExplorers: {
      default: {
        name: 'zkExplorer',
        url: 'https://sepolia.explorer.zksync.io/',
      },
    },
    contracts: {
      multicall3: {
        address: '0xF9cda624FBC7e059355ce98a31693d299FACd963',
      },
    },
    testnet: true,
  },
  {
    serializers: serializersZkSync,
    formatters: formattersZkSync,
  },
)

**Comment by Rubilmax** [comment]
Thanks for asking!
